/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Gato;
import clases.PlayWave;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author gerardo
 */
public class FrmTablero extends javax.swing.JFrame {

    private Gato g1 = new Gato();
    private JLabel[] tablero = new JLabel[9];
    private FrmIntro frmIntro = new FrmIntro(g1);
    private boolean banJuego = false;
    private boolean iniciar = false;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmTablero() {
        initComponents();
        tablero[0] = lblImagen1;
        tablero[1] = lblImagen2;
        tablero[2] = lblImagen3;
        tablero[3] = lblImagen4;
        tablero[4] = lblImagen5;
        tablero[5] = lblImagen6;
        tablero[6] = lblImagen7;
        tablero[7] = lblImagen8;
        tablero[8] = lblImagen9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen1 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen4 = new javax.swing.JLabel();
        lblImagen5 = new javax.swing.JLabel();
        lblImagen6 = new javax.swing.JLabel();
        lblImagen7 = new javax.swing.JLabel();
        lblImagen8 = new javax.swing.JLabel();
        lblImagen9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnNuevoJuego = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JuegoGato V 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        lblImagen1.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen1MouseClicked(evt);
            }
        });

        lblImagen3.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen3MouseClicked(evt);
            }
        });

        lblImagen2.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen2MouseClicked(evt);
            }
        });

        lblImagen4.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen4MouseClicked(evt);
            }
        });

        lblImagen5.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen5MouseClicked(evt);
            }
        });

        lblImagen6.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen6MouseClicked(evt);
            }
        });

        lblImagen7.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen7MouseClicked(evt);
            }
        });

        lblImagen8.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen8MouseClicked(evt);
            }
        });

        lblImagen9.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png"))); // NOI18N
        lblImagen9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("Juego del Gato");

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comience a Jugar");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevoJuego.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnNuevoJuego.setText("Nuevo Juego");
        btnNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoJuegoActionPerformed(evt);
            }
        });

        btnSalir1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalir1.setText("Creditos");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen1MouseClicked

        // TODO add your handling code here:
        tirar(0);


    }//GEN-LAST:event_lblImagen1MouseClicked

    private void lblImagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen2MouseClicked

        // TODO add your handling code here:
        tirar(1);
    }//GEN-LAST:event_lblImagen2MouseClicked

    private void lblImagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen3MouseClicked

        // TODO add your handling code here:
        tirar(2);
    }//GEN-LAST:event_lblImagen3MouseClicked

    private void lblImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen4MouseClicked

        // TODO add your handling code here:
        tirar(3);
    }//GEN-LAST:event_lblImagen4MouseClicked

    private void lblImagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen5MouseClicked

        // TODO add your handling code here:
        tirar(4);
    }//GEN-LAST:event_lblImagen5MouseClicked

    private void lblImagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen6MouseClicked

        // TODO add your handling code here:
        tirar(5);
    }//GEN-LAST:event_lblImagen6MouseClicked

    private void lblImagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen7MouseClicked

        // TODO add your handling code here:
        tirar(6);
    }//GEN-LAST:event_lblImagen7MouseClicked

    private void lblImagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen8MouseClicked

        // TODO add your handling code here:
        tirar(7);
    }//GEN-LAST:event_lblImagen8MouseClicked

    private void lblImagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen9MouseClicked

        // TODO add your handling code here:
        tirar(8);
    }//GEN-LAST:event_lblImagen9MouseClicked

    private void btnNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoJuegoActionPerformed

       
        // TODO add your handling code here:
        g1.reiniciar();
        frmIntro = new FrmIntro(g1);
        frmIntro.setVisible(true);
        g1.setBanTurnoJ1(true);
        banJuego = true;
    }//GEN-LAST:event_btnNuevoJuegoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        System.exit(0);

        // TODO add your handling code here:

    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // TODO add your handling code here:
        reiniciar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * manda el mensaje de datos del juego
     * @param evt 
     */
    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed

        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Este juego es una idea original"
                + " de: \n  Apolinar Trejo Cuevas \n Desarrollado por:"
                + "\n Juan Gerardo  Andrade Ortiz \n UTNG \n GSI1331 \n "
                + "DESARROLLO APLICACIONES I");
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     * pone la imagen correspondiente segun el tiro,
     * y verifica si se ha ganado segun las combinaciones
     * que se pueden dar
     */
    private void tirar(int pos) {
        if (banJuego) {

            if (g1.verificar(pos)) {
                g1.setTiro(pos);
                if (g1.isBanTurnoJ1()) {
                    if (g1.getTiro1() == 1) {

                        tablero[pos].setIcon(new ImageIcon(getClass().
                                getResource("/pics_JuegoGato/x.png")));
                    } else {
                        tablero[pos].setIcon(new ImageIcon(getClass().
                                getResource("/pics_JuegoGato/o.png")));
                    }

                } else {
                    if (g1.getTiro2() == 1) {
                        tablero[pos].setIcon(new ImageIcon(getClass().
                                getResource("/pics_JuegoGato/x.png")));
                    } else {
                        tablero[pos].setIcon(new ImageIcon(getClass().
                                getResource("/pics_JuegoGato/o.png")));
                    }

                }
                explosion();
                if (g1.yaGano() != 0 && (g1.isBanTurnoJ1() && 
                        g1.getTiro1() == 1 || !g1.isBanTurnoJ1() &&
                        g1.getTiro2() == 1)) {

                    
                    exclamacion();
                    // tiro = equis
                    switch (g1.yaGano()) {
                        case 1: // fila #1
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            break;

                        case 2: // fila #1
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            break;

                        case 3: // fila #1
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_h.png")));
                            break;
                        case 4: // fila #4
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            break;
                        case 5: // fila #5
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            break;

                        case 6: // fila #6
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_v.png")));
                            break;

                        case 7: // fila #7
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_d1.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_d1.png")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_d1.png")));
                            break;
                        case 8: // fila #8
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_d2.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_d2.png")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/x_d2.png")));
                            break;
                    }

                } else if (g1.yaGano() != 0 && (g1.isBanTurnoJ1() && 
                        g1.getTiro1() == 2 || !g1.isBanTurnoJ1() && 
                        g1.getTiro2() == 2)) {

                    
                    exclamacion();
                    switch (g1.yaGano()) {
                        case 1: // fila #1
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            break;

                        case 2: // fila #1
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            break;

                        case 3: // fila #1
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_h.png")));
                            break;
                        case 4: // fila #4
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            tablero[3].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            break;
                        case 5: // fila #5
                            tablero[1].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            tablero[7].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            break;

                        case 6: // fila #6
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            tablero[5].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_v.png")));
                            break;

                        case 7: // fila #7
                            tablero[0].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_d1.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_d1.png")));
                            tablero[8].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_d1.png")));
                            break;
                        case 8: // fila #8
                            tablero[2].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_d2.png")));
                            tablero[4].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_d2.png")));
                            tablero[6].setIcon(new ImageIcon(getClass().
                                    getResource("/pics_JuegoGato/o_d2.png")));
                            break;
                    }
                }
            }
            // gano con la 0
            if (g1.yaGano() != 0 && g1.isBanTurnoJ1()) {

                JOptionPane.showMessageDialog(this, "Ya Gano " + g1.getJugador1());
            } else if (g1.yaGano() != 0 && !g1.isBanTurnoJ1()) {
                JOptionPane.showMessageDialog(this, "Ya gano " + g1.getJugador2());
            } else if (g1.esEmpate()) {
                JOptionPane.showMessageDialog(this, "Empate Chavos!");
            }

            g1.cambiarTurno();
        }
    }

    /**
     * reinicia los datos y las imagenes que se utilizan
     */
    public void reiniciar() {
        for (int i = 0; i < 9; i++) {
            tablero[i].setIcon(new ImageIcon(getClass().getResource("/pics_JuegoGato/vacio.png")));
        }
        g1.reiniciar();
        

        /**
         * genera el sonido de explosion
         */
    }
    public void explosion() {
        try {

            PlayWave pw1;
            String url = "/media/explos.wav";
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (Exception e) {
            System.out.println("error en la sintaxis del archivo");
        }
    }

    /**
     * genera el sonido de exclamacion
     */
    public void exclamacion() {
        try {

            PlayWave pw1;
            String url = "/media/wow.wav";
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (Exception e) {
            System.out.println("error en la sintaxis del archivo");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablero().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoJuego;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblImagen4;
    private javax.swing.JLabel lblImagen5;
    private javax.swing.JLabel lblImagen6;
    private javax.swing.JLabel lblImagen7;
    private javax.swing.JLabel lblImagen8;
    private javax.swing.JLabel lblImagen9;
    // End of variables declaration//GEN-END:variables
}
